In [55]:
from kaggle.api.kaggle_api_extended import KaggleApi

In [56]:
api = KaggleApi()
api.authenticate()

api.dataset_download_files(
    'najir0123/walmart-10k-sales-datasets',
    path='data/',
    unzip=True
)

Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets

In [57]:
import pandas as pd

In [58]:
walmart_dataset = pd.read_csv('data/Walmart.csv')

In [59]:
walmart_dataset.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [60]:
walmart_dataset.shape

(10051, 11)

In [61]:
walmart_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [62]:
walmart_dataset.duplicated().sum()

np.int64(51)

In [63]:
walmart_dataset.drop_duplicates(inplace=True)

In [64]:
walmart_dataset.duplicated().sum()

np.int64(0)

In [65]:
walmart_dataset.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [66]:
walmart_dataset.dropna(inplace=True)

In [67]:
walmart_dataset.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   str
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(3), int64(1), str(7)
memory usage: 934.6 KB

In [68]:
walmart_dataset['unit_price'] = walmart_dataset['unit_price'].str.replace('$', '')

In [69]:
walmart_dataset['unit_price']=walmart_dataset['unit_price'].astype(float)

In [70]:
walmart_dataset.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

In [71]:
walmart_dataset['Total']=walmart_dataset['unit_price'] * walmart_dataset['quantity']

In [72]:
walmart_dataset.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,Total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [73]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\ssand\appdata\local\programs\python\python311\lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",        # or your server IP
    user="root",             # your username
    password="root",
    database="sqlproject",
    allow_local_infile=True
)

cursor = conn.cursor()

print("Connected successfully!")

Connected successfully!

In [75]:
cursor.execute("SHOW DATABASES")

for db in cursor.fetchall():
    print(db)

('bank_loan',)
('information_schema',)
('my_project',)
('mysql',)
('newschema',)
('performance_schema',)
('sqlproject',)
('swiggy_modeling',)
('swiggy_project',)
('sys',)
('test',)
('vanyas_learning',)

In [76]:
walmart_dataset.shape

(9969, 12)

In [77]:
walmart_dataset.to_csv("walmart cleand.csv",index=False)

In [78]:
print(walmart_dataset.columns)

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'Total'],
      dtype='str')

In [79]:
cursor.execute("""
CREATE TABLE walmart (
    invoice_id VARCHAR(50),
    branch VARCHAR(10),
    city VARCHAR(50),
    category VARCHAR(50),
    unit_price FLOAT,
    quantity INT,
    date DATE,
    time TIME,
    payment_method VARCHAR(50),
    rating FLOAT,
    profit_margin FLOAT,
    total FLOAT
)
""")

In [80]:
cursor.execute("SET GLOBAL local_infile = 1;")

In [81]:
cursor.execute("""
LOAD DATA LOCAL INFILE 'C:/Users/ssand/Downloads/DA projects/SQL/project 1 sql/walmart cleand.csv'
INTO TABLE walmart
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 ROWS
""")

In [82]:
conn.commit()

cursor.execute("SELECT COUNT(*) FROM walmart")
print("Rows:", cursor.fetchone()[0])

Rows: 9969